
    create table db_properties (
       id int8 generated by default as identity,
        address varchar(255),
        date timestamp,
        tenant varchar(255),
        primary key (id)
    );
create table db_properties (id int8 generated by default as identity, address varchar(255), date timestamp, tenant varchar(255), primary key (id));
INSERT INTO db_properties(tenant, address, date) VALUES ('Jim Halpert', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Dwight Schrute', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Stanley Hudson', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Creed Bratton', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Kevin Malone', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Phyllis Smith', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Erin Hannon', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Toby Flenderson', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Michael Scott', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
create table db_properties (id int8 generated by default as identity, address varchar(255), date timestamp, tenant varchar(255), primary key (id));
INSERT INTO db_properties(tenant, address, date) VALUES ('Jim Halpert', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Dwight Schrute', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Stanley Hudson', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Creed Bratton', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Kevin Malone', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Phyllis Smith', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Erin Hannon', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Toby Flenderson', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
INSERT INTO db_properties(tenant, address, date) VALUES ('Michael Scott', '1725 Slough Avenue in Scranton, PA.', '2022-03-11 08:00:00');
